package eddfarmacias.Interfaz;

import eddfarmacias.EscrLect;


/**
 *
 * @author moica
 */
public class Interfaz extends javax.swing.JFrame {
    
    MultiLista ml = new MultiLista();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        initComponents();
        EscrLect a = new EscrLect();
        ml = a.SacaDatos();
        if (ml == null)
        {
            ml = new MultiLista();
        }
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFarmacia = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnCiudades = new javax.swing.JButton();
        btnSucursal = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 153, 255));
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFarmacia.setBackground(new java.awt.Color(51, 51, 255));
        btnFarmacia.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btnFarmacia.setText("Farmacias");
        btnFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btnsalir.setBackground(new java.awt.Color(51, 51, 255));
        btnsalir.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.setToolTipText("");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        btnCiudades.setBackground(new java.awt.Color(51, 51, 255));
        btnCiudades.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btnCiudades.setText("Ciudades");
        btnCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        btnSucursal.setBackground(new java.awt.Color(51, 51, 255));
        btnSucursal.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btnSucursal.setText("Sucursales");
        btnSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        btnProductos.setBackground(new java.awt.Color(51, 51, 255));
        btnProductos.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 470, 140));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaciaActionPerformed
        Farmacias f = new Farmacias(ml);
        f.setVisible(true);
        ml = Farmacias.mul;
        this.setVisible(false);
    }//GEN-LAST:event_btnFarmaciaActionPerformed

    private void btnCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadesActionPerformed
        Ciudades c = new Ciudades(ml);
        c.setVisible(true);
        ml = Ciudades.mulC;
        this.setVisible(false);
    }//GEN-LAST:event_btnCiudadesActionPerformed

    private void btnSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalActionPerformed
        Sucursales s = new Sucursales(ml);
        s.setVisible(true);
        ml = Sucursales.mul;
        this.setVisible(false);
    }//GEN-LAST:event_btnSucursalActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        Productos p = new Productos(ml);
        p.setVisible(true);
        ml = Productos.mul;
        this.setVisible(false);
    }//GEN-LAST:event_btnProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCiudades;
    private javax.swing.JButton btnFarmacia;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSucursal;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
